[package]
name = "adventofcode2021"
version = "0.1.0"
authors = ["Mark Triggs <mark@dishevelled.net>"]
edition = "2021"

[dependencies]
regex = "*"
lazy_static = "*"
rand = "*"
itertools = "*"
anyhow = "*"
